In [2]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

#tb.loc[tb['Instrument Classification (ISO 10962 CFI code)'].isin(['JFTXFP'])]
#tb.plot.hist(tb.groupby(['Trading platform']).Price.agg(['mean', max]))
#tb.describe()
#print(tb.shape)

df = pd.read_csv('C:/Users/inald/Documents/NWMprod/wetransfer-0f4d76/rts27.csv')

#print(df.shape)
#df.head(20)

,id,bank_name,legal_entity_name,file_name,date_of_trading_day,instrument_identifier,instrument_classification,order_request_quotes_received,executed_transactions,total_value_of_transactions,...,median_transaction_size_eur,median_transaction_size_gbp,median_size_request_quotes_eur,median_size_request_quotes_gbp,smartie_instrument_name,data_quality_flag,egb_eligible_flag,year_quarter,business,central_bank_isin_flag
101,67771595,Morgan Stanley,Morgan Stanley & Co. International Plc,mifid2_rts27_forwards_T1_T2_T6.csv,2018-09-28 00:00:00,EZ24NVRGSWM1,JFTXFP,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018 Q3,NaN,NaN
102,67771596,Morgan Stanley,Morgan Stanley & Co. International Plc,mifid2_rts27_forwards_T1_T2_T6.csv,2018-09-06 00:00:00,NaN,JFTXFP,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018 Q3,NaN,NaN
103,67771597,Morgan Stanley,Morgan Stanley & Co. International Plc,mifid2_rts27_forwards_T1_T2_T6.csv,2018-07-13 00:00:00,EZ6HV8SZ0GB1,JFTXFP,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018 Q3,NaN,NaN
104,67771598,Morgan Stanley,Morgan Stanley & Co. International Plc,mifid2_rts27_forwards_T1_T2_T6.csv,2018-08-31 00:00:00,NaN,JFTXFP,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018 Q3,NaN,NaN
105,67771599,Morgan Stanley,Morgan Stanley & Co. International Plc,mifid2_rts27_forwards_T1_T2_T6.csv,2018-07-20 00:00:00,EZW2B7BGWGS3,JFTXFP,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018 Q3,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12899305,29331807,Natwest Markets,Natwest Markets PLC,RTS27_Table6_LikelihoodOfExecution_20180401_20...,2018-04-16 00:00:00,EZV9F8FK9N90,JFTXFP,1.0,NaN,NaN,...,NaN,NaN,5.000000e+05,NaN,NaN,NaN,NaN,2018 Q2,NaN,NaN
12899307,29331809,Natwest Markets,Natwest Markets PLC,RTS27_Table6_LikelihoodOfExecution_20180401_20...,2018-04-16 00:00:00,EZVB0FHV4HR5,JFTXFP,1.0,NaN,NaN,...,NaN,NaN,1.190622e+07,NaN,NaN,NaN,NaN,2018 Q2,NaN,NaN
12899308,29331810,Natwest Markets,Natwest Markets PLC,RTS27_Table6_LikelihoodOfExecution_20180401_20...,2018-04-16 00:00:00,EZVB0H00LCW1,JFTXFP,3.0,2.0,1972353.34,...,986176.67,NaN,3.591434e+05,NaN,NaN,NaN,NaN,2018 Q2,NaN,NaN
12899310,29331812,Natwest Markets,Natwest Markets PLC,RTS27_Table6_LikelihoodOfExecution_20180401_20...,2018-04-16 00:00:00,EZVB63CGLBZ7,JFTXFP,5.0,NaN,NaN,...,NaN,NaN,1.616815e+07,NaN,NaN,NaN,NaN,2018 Q2,NaN,NaN
12899311,29331813,Natwest Markets,Natwest Markets PLC,RTS27_Table6_LikelihoodOfExecution_20180401_20...,2018-04-16 00:00:00,EZVB826LVWC0,JFTXFP,1.0,NaN,NaN,...,NaN,NaN,1.298312e+04,NaN,NaN,NaN,NaN,2018 Q2,NaN,NaN

In [21]:
#Columns deemed unneccessary for this task
dfFiltered = df.drop(['file_name','designated_market_makers','legal_entity_name', 'systematic_internaliser_flag'], axis = 1)

#Filters the code to FX forwards only
dfFiltered = dfFiltered.loc[(df['instrument_classification']).astype(str).str.contains("JF")]

#Drops the columns of which half of the fields have no data.
dfFiltered = dfFiltered.dropna(axis=1, thresh=2000000)

dfFiltered

,id,bank_name,date_of_trading_day,instrument_identifier,instrument_classification,order_request_quotes_received,executed_transactions,order_request_quotes_can_wdrwn,order_request_quotes_modified,median_size_request_quotes,active,date_created,source_instrument_ccy,source_market_segment,traded_in_natwest_markets,source_instrument_name,median_size_request_quotes_eur,median_size_request_quotes_gbp,year_quarter
100,67771594,Morgan Stanley,2018-09-13 00:00:00,EZ43HP8WC2Y3,JFTXFC,0.0,NaN,NaN,NaN,NaN,Y,2019-01-15 15:01:55,USD|BRL,NaN,Yes,NaN,NaN,NaN,2018 Q3
101,67771595,Morgan Stanley,2018-09-28 00:00:00,EZ24NVRGSWM1,JFTXFP,0.0,NaN,NaN,NaN,NaN,Y,2019-01-15 15:01:55,USD|SEK,NaN,Yes,NaN,NaN,NaN,2018 Q3
102,67771596,Morgan Stanley,2018-09-06 00:00:00,NaN,JFTXFP,1.0,NaN,NaN,NaN,NaN,Y,2019-01-15 15:01:55,USD|TRY,NaN,No,NaN,NaN,NaN,2018 Q3
103,67771597,Morgan Stanley,2018-07-13 00:00:00,EZ6HV8SZ0GB1,JFTXFP,1.0,NaN,NaN,NaN,NaN,Y,2019-01-15 15:01:55,USD|TRY,NaN,Yes,NaN,NaN,NaN,2018 Q3
104,67771598,Morgan Stanley,2018-08-31 00:00:00,NaN,JFTXFP,1.0,NaN,NaN,NaN,NaN,Y,2019-01-15 15:01:55,USD|DKK,NaN,No,NaN,NaN,NaN,2018 Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12899305,29331807,Natwest Markets,2018-04-16 00:00:00,EZV9F8FK9N90,JFTXFP,1.0,NaN,1.0,NaN,5.000000e+05,Y,2019-01-03 11:50:47,"BHD,EUR",NaN,Yes,NaN,5.000000e+05,NaN,2018 Q2
12899307,29331809,Natwest Markets,2018-04-16 00:00:00,EZVB0FHV4HR5,JFTXFP,1.0,NaN,1.0,NaN,1.190622e+07,Y,2019-01-03 11:50:47,"NZD,USD",NaN,Yes,NaN,1.190622e+07,NaN,2018 Q2
12899308,29331810,Natwest Markets,2018-04-16 00:00:00,EZVB0H00LCW1,JFTXFP,3.0,2.0,1.0,NaN,3.591434e+05,Y,2019-01-03 11:50:47,"EUR,USD",NaN,Yes,NaN,3.591434e+05,NaN,2018 Q2
12899310,29331812,Natwest Markets,2018-04-16 00:00:00,EZVB63CGLBZ7,JFTXFP,5.0,NaN,4.0,NaN,1.616815e+07,Y,2019-01-03 11:50:47,"GBP,USD",NaN,Yes,NaN,1.616815e+07,NaN,2018 Q2
12899311,29331813,Natwest Markets,2018-04-16 00:00:00,EZVB826LVWC0,JFTXFP,1.0,NaN,1.0,NaN,1.298312e+04,Y,2019-01-03 11:50:47,"EUR,RUB",NaN,Yes,NaN,1.298312e+04,NaN,2018 Q2

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Select target
y = df['date_created']
# To keep things simple, we'll use only numerical predictors
predictors = df.drop(['date_created'], axis=1)
X = df

# Divide data into training and validation subsets
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0)

In [17]:
from sklearn.impute import SimpleImputer

# Imputation
my_imputer = SimpleImputer(missing_values='np.nan', strategy = 'most_frequent')
imputed_X_train = pd.DataFrame(my_imputer.fit_transform(X_train))
imputed_X_valid = pd.DataFrame(my_imputer.transform(X_valid))

# Imputation removed column names; put them back
imputed_X_train.columns = X_train.columns
imputed_X_valid.columns = X_valid.columns

print(imputed_X_train.columns.isnull().sum())

Categorical variables:
['bank_name', 'legal_entity_name', 'file_name', 'instrument_identifier', 'instrument_classification', 'active', 'source_instrument_desc', 'source_instrument_ccy', 'source_market_segment', 'smartie_instrument_id', 'systematic_internaliser_flag', 'liquidity_provider_flag', 'traded_in_natwest_markets', 'source_instrument_name', 'smartie_instrument_name', 'data_quality_flag', 'egb_eligible_flag', 'year_quarter', 'business', 'central_bank_isin_flag']

TypeError: Encoders require their input to be uniformly strings or numbers. Got ['NoneType', 'str']

In [19]:
from sklearn.preprocessing import LabelEncoder

# Get list of categorical variables
s = (X_train.dtypes == 'object')
object_cols = list(s[s].index)

print("Categorical variables:")
print(object_cols)

# Make copy to avoid changing original data 
label_X_train = X_train.copy()
label_X_valid = X_valid.copy()

# Apply label encoder to each column with categorical data
label_encoder = LabelEncoder()
for col in object_cols:
    label_encoder.fit(pd.concat([X_train[col], X_valid[col]], axis=0, sort=False))
    label_X_train[col] = label_encoder.transform(X_train[col])
    label_X_valid[col] = label_encoder.transform(X_valid[col])

MemoryError: Unable to allocate 409. GiB for an array with shape (662704, 662704) and data type uint8

In [ ]:

pd.get_dummies(df)